### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [Kilmyashkin/kottans#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by Kilmyashkin** [comment]
https://raw.githubusercontent.com/Kilmyashkin/kottans/master/week01/week01-0/Screenshot%20from%202016-05-21%2017%3A40%3A38%20-%204.png

**Comment by sudodoki** [comment]
👍
